FROM openjdk:17-alpine AS runner

WORKDIR /app
ARG JAR_FILE=build/libs/app-tech-0.0.1-SNAPSHOT.jar
ENV TZ=Asia/Seoul
COPY ${JAR_FILE} /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","app.jar"]